### ISSUE TITLE
Using ":IronRepl" does nothing.

### ISSUE THREAD

**Issue by JulioHC00** [hkupty/iron.nvim#204]
Hi, I have just isntalled iron.nvim and configured it but doing ":IronRepl" does nothing. It doesn't throw an error, it just does nothing.

I have created the lua file and put "luafile $HOME/.config/nvim/plugins.lua" into my init.vim. The plugin is working because if I try to do ":IronRepl" into a file that's not .py I get "There's no REPL definition for current filetype foo".

In case it helps, my list of plugins is
```
'vim-scripts/indentpython.vim'
'dense-analysis/ale'
'nvie/vim-flake8'
'vim-auto-save'
'tpope/vim-surround'
'gerw/vim-latex-suite'
'morhetz/gruvbox'
'lervag/vimtex'
'vim-python/python-syntax'
'ycm-core/YouCompleteMe'
'MarcWeber/vim-addon-mw-utils'
'tomtom/tlib_vim'
'garbas/vim-snipmate'
'AndrewRadev/dsf.vim'
'godlygeek/tabular'
'hkupty/iron.nvim'
```
And the contents of the plugins.lua file

```
local iron = require('iron')

iron.core.set_config {
  preferred = {
    python = "ipython3"
  }
}
```
EDIT: I've tried doing ":IronRepl" after removing all plugins and configuration (in init.vim) but iron.nvim and the same still happens, so I have no clue as to where the issue is coming from.

**Comment by hkupty** [comment]
That is super weird.
It can't be when trying to locate the binary because [it would fail with an error](https://github.com/hkupty/iron.nvim/blob/master/lua/iron/lowlevel.lua#L43-L45).
It can be though that [your preferred repl points to a repl definition that does not exist](https://github.com/hkupty/iron.nvim/blob/master/lua/iron/lowlevel.lua#L35).
I'll make sure to add a check for that.

Furthermore, I think this whole way of setting up repls is not working great and is a source of confusion.

From what I can see, the issue would be that `ipython3` doesn't point to [one of the default python definitions](https://github.com/hkupty/iron.nvim/blob/master/lua/iron/fts/python.lua#L44-L50)

Is `ipython3` the binary name? If you have both `ipython` and `ipython3` and `ipython` points to python 2.x, then the immediate solution would be to create a new definition for `ipython3`.

A proper fix for this would be to simplify this config model and make it simpler for people to configure their repls of choice, but I can't promise this will land anytime this month even with my best efforts.

Hopefully, I'll be able to find more time to devote to opensource in the coming months as things get more stable in my life and this new way of configuring iron.nvim will arrive soon enough.

For now, I present you two choices:

- if `ipython` also runs for python 3, use that as preferred.
- if you can't use `ipython`, you'll have to add a new configuration for `ipython3`, like this:
```lua
iron.core.add_repl_definitions {
  python = {
    ipython3 = {
      command = {"ipython3", "--no-autoindent"},
      format = require("iron.fts.python").ipython.format -- this is required for bracketed paste
    }
  }
}
```

Let me know how this goes.

**Comment by JulioHC00** [comment]
I had managed to get it half working, defining (wrongly as I can now see) a new configuration. I say wrongly because there were problems with sending multi-line chunks of code, but with your solution it's now working like a charm! It wasn't an issue with the binary because that's precisely what I got if I used ipython (which for some reason I can't  get to work, only ipython3).

It doesn't solve the problem of not getting any kind of error when I hadn't defined "ipython3". Perhaps a quick solution would be to add a short explanation of how you have to configure the "plugins.lua" file for people without experience, like me. In any case, thank you for the solution! And I am grateful for the great plugin and all the effort you put into it!

**Comment by hkupty** [comment]
Glad it worked!
