### ISSUE TITLE
What REPLs does this interface with?

### ISSUE THREAD

**Issue by brendenhoffman** [hkupty/iron.nvim#271]
This looks like a really nice, handy plugin, but I can't figure out by looking at it what it can do. I despise working in REPLs, so anything that lets me type in vim and push it into the REPL is a godsend. I used vim-slime a while back for sql, it was not an intended use case, but it was able to push code into any REPL. For sql I just had to open it in tmux, it was very clunky and I don't like using tmux all that much, but it was better than typing in the REPL and reduced the amount of mistakes I made.
Can I use this with sql? Its really hard to tell how its working by looking at this page... if its just opening up a shell in your vim window I dont see why it cant interface with sql, right? I am trying to replace all my neovim plugins with ones written in lua, so if it works how I think it does then its exactly what I am looking for and would actually be a huge upgrade over vim-slime.

**Comment by hkupty** [comment]
Hi @brendenhoffman,

Sorry for the delay in answering - summer vacations are taking some my attention out of the internet.

It does work with any programming language that you'd have a repl to interact to. It is language agnostic, so it basically works by bridging the source file(s) and the REPL window for you, by providing a few commands, functions and keybindings to allow you to copy chunks of text from one window (source code) to the other (repl), without having to leave the window you're in.

If you want to use it with SQL, which is not a "supported out-of-the-box language", you can simply configure it to do so like this:

```lua
local iron = require("iron.core")

iron.setup {
  config = {
    repl_definition = {
      sql = {
        command = {"psql", ...} -- You can configure your flags here. 
      }   
    },
  }
}
    ```

A new feature will be implemented to allow you to configure providers instead of simple commands, meaning you can supply functions that return your repl definition. This might be interesting for you so you'll be able to, through the function, acquire username and passowrd for your SQL connections, which might be a bit unsafe to store in a dotfile in git.

Let me know if you still have any doubts or if I can help you any further.

cheers,
Henry

**Comment by brendenhoffman** [comment]
Awesome! Sounds like a great tool, good work so far, definitely adding it to my tool belt.

**Comment by hkupty** [comment]
Thanks a lot! Please don't refrain from opening up an issue if you have any further questions.

Best regards,
Henry
