### ISSUE TITLE
Don't set winfixwidth

### ISSUE THREAD

**Issue by jolars** [hkupty/iron.nvim#287]
On the following line the option `winfixwidth` is hardcoded to `true`.

https://github.com/hkupty/iron.nvim/blob/26a6c70fa81d0b4c514da5546fc7db125c6a1c4a/lua/iron/view.lua#L14

This is messing with my setup and I cannot (easily) get around it since it is set after the vim command that is passed through the `repl_open_cmd`.

Since anyone who wants winfixwidth could just use

```lua
repl_open_cmd = "vertical botright split | set winfixwidth"
```

it would make more sense to me to just remove the hard-coding of `winfixwidth`.

**Comment by hkupty** [comment]
Hi @jolars,

I didn't really think this would cause issues. Sure, I can make it configurable.

**Comment by hkupty** [comment]
I gave it a thought and I can't just not set it because it will likely break the behavior that other people's are used to after this being the default for so long, so instead I made it customizable.
It is set by default now only if you use the new, fluid `views` api, which is set by default. If you supply the command directly it won't do anything.
Also, you can still use the `views` api and overwrite the default values to not set `winfixwidth` and `winfixheight` if you supply those keys as options and overwrite them.

I guess this is a pretty decent solution for the problem, right? If you use the API you get defaults but you're free to do whatever you want if you prefer commands.. wdyt?

**Comment by jolars** [comment]
Great! Yes I think this is probably the best solution. I guess it might mess a bit with someone who uses a custom vim repl command and expects fixed widths/heights, but since it's not really going to break anything important I think that should be okay without going through the hoops of deprecating and so on.

Thanks a lot for this and keep up the good work with the plugin!
