### ISSUE TITLE
Use your current python virtual env or conda env in IronRepl

### ISSUE THREAD

**Issue by kuang22** [hkupty/iron.nvim#318]
When I begin to use this plugin, at first I am excited about its features. However, when I tailor it towards my work flow, I ran into some problems. Here is my **problem described as follows**:
When I write python scripts, I use "conda activate myenv" in my shell, then I open neovim to write python script. At this step, I use IronRepl to open an interactive window. What I expected is that the ipython/python interpreter in IronRepl is running in "myenv". However, with the default config, the IronRepl would not care about "myenv", which is frustrating. There are two issues related to this problem, but in a long time ago, those solutions do not agree to the updated IronRepl code.
Here is **my quick solution**:
In iron.core.setup, add this config
```lua
config = {
  ...
  repl_definition = {
    ...
    python = {command = {os.getenv("CONDA_PREFIX") .. "/bin/ipython"} }
}
  ...
}
```
For those who use _conda_ as well, you can apply above code directly. And for those use other virtualenv, you could modify the environment variable to satisfy your goal.
Hope this could help those who ran into the same problem as my situation. 
BTW, wonderful plugin and thanks to the developer! :)

**Comment by mikedecr** [comment]
Another way to handle this is to include something in your shell profile (eg `.bashrc` or `.zshrc`) that prevents new terminals from forcefully activating a new base environment. See [here](https://www.reddit.com/r/neovim/comments/ga0s7w/comment/foxs2m8/?utm_source=reddit&utm_medium=web2x&context=3).

In short:

- when Iron opens a REPL, it is implicitly opening a terminal within neovim first
- if your `.*rc` file includes the normal conda boilerplate, it will open this terminal in a _new base environment_ instead of preserving the current environment, so you need to take extra steps to get back into your venv for python (or whatever REPL you are running)
- The linked discussion provides a control flow for your `.rc` file to prevent activating that new base env. As a result, the Iron REPL opens in the same environment where your neovim session was already running.

If you implement the fix at the level of your `*.rc`, no Iron config changes are required, and you get the added bonus that _all_ new neovim terminals will use the environment where nvim is currently running

**Comment by kuang22** [comment]
> Another way to handle this is to include something in your shell profile (eg `.bashrc` or `.zshrc`) that prevents new terminals from forcefully activating a new base environment. See [here](https://www.reddit.com/r/neovim/comments/ga0s7w/comment/foxs2m8/?utm_source=reddit&utm_medium=web2x&context=3).
> 
> In short:
> 
> * when Iron opens a REPL, it is implicitly opening a terminal within neovim first
> * if your `.*rc` file includes the normal conda boilerplate, it will open this terminal in a _new base environment_ instead of preserving the current environment, so you need to take extra steps to get back into your venv for python (or whatever REPL you are running)
> * The linked discussion provides a control flow for your `.rc` file to prevent activating that new base env. As a result, the Iron REPL opens in the same environment where your neovim session was already running.
> 
> If you implement the fix at the level of your `*.rc`, no Iron config changes are required, and you get the added bonus that _all_ new neovim terminals will use the environment where nvim is currently running

Seem cool, I'll try that later, thx!

**Comment by MarcelPa** [comment]
I found this behavior to occur when you do not have IPython installed in the new conda environment. As a repl will look for IPython, it will go to the IPython it finds on the system level - including the python version found there. 
With IPython installed via conda, I do not need the extra config you described, the default config is sufficient.
Hope that helps!

**Comment by kuang22** [comment]
> 

This is true. Thus we do not need the extra config actually. I will close this issue.
