### ISSUE TITLE
I can't install iron.nvim

### ISSUE THREAD

**Issue by lucaspeixotot** [hkupty/iron.nvim#48]
I'm a young man in the vim world and the programming. May you explain more detailed how to install iron-nvim, nvim-ipy and etc? Thank you very much in advance.

**Comment by hkupty** [comment]
Hi!

I'll reply here since hopefully this will change in the future.

You'll need either [vim-plug](https://github.com/junegunn/vim-plug) or [dein](https://github.com/Shougo/dein.vim) so you can install plugins on vim. Please follow either instructions first.

After that, add either of the following blocks on your init.vim:
```vim
" Vim-plug
Plug 'hkupty/iron.nvim'

" dein
call dein#add('hkupty/iron.nvim')
```
Reload your init.vim and install iron.

The last step is to run `:UpdateRemotePlugins` and reload neovim.

If anything goes wrong, don't refrain from reopening this issue!

Cheers,
Henry J. Kupty
